name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11 (or preferred version)
      uses: actions/setup-java@v4
      with:
        java-version: '11'  # Update with your desired Java version (e.g., 11 or 17)
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Update Gradle Wrapper Version to 6.0
      run: ./gradlew wrapper --gradle-version 6.0  # Update to your preferred Gradle version (e.g., 6.0)

    - name: Build with Gradle Wrapper
      run: ./gradlew build
